### ISSUE TITLE
Move location for some settings

### ISSUE THREAD

**Issue by ExtraMyBB** [ExtraMyBB/Advanced-Ads-Manager-Plugin#3]
We have decided to move the following settings : "Who can add an advertisement" and "Who cannot see an advertisement" from "Settings" section into "User Group" section by creating a new tab with permissions.

**Comment by Mihu90** [comment]
Please check the last commit. We have to test all changes implemented and then to close this ticket.

**Comment by Harald-R** [comment]
Everything works fine. Ticket closed.
